2025-02-05 11:33:53,052 INFO    MainThread:3679 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/sofiatete/Deep_learning_for_medical_imaging/wandb/run-20250205_113353-vx8iu149/logs/debug.log
2025-02-05 11:33:53,052 INFO    MainThread:3679 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/sofiatete/Deep_learning_for_medical_imaging/wandb/run-20250205_113353-vx8iu149/logs/debug-internal.log
2025-02-05 11:33:53,052 INFO    MainThread:3679 [wandb_init.py:init():756] calling init triggers
2025-02-05 11:33:53,052 INFO    MainThread:3679 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-02-05 11:33:53,052 INFO    MainThread:3679 [wandb_init.py:init():789] starting backend
2025-02-05 11:33:53,052 INFO    MainThread:3679 [wandb_init.py:init():793] sending inform_init request
2025-02-05 11:33:53,053 INFO    MainThread:3679 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-02-05 11:33:53,053 INFO    MainThread:3679 [wandb_init.py:init():808] backend started and connected
2025-02-05 11:33:53,057 INFO    MainThread:3679 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-02-05 11:33:53,059 INFO    MainThread:3679 [wandb_init.py:init():901] updated telemetry
2025-02-05 11:33:53,108 INFO    MainThread:3679 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-02-05 11:35:23,514 ERROR   MainThread:3679 [wandb_init.py:init():1471] error in wandb.init()
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 950, in init
    raise CommError(
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-02-05 11:50:21,598 INFO    MainThread:3679 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/sofiatete/Deep_learning_for_medical_imaging/wandb/run-20250205_115021-8rrl7mwb/logs/debug.log
2025-02-05 11:50:21,598 INFO    MainThread:3679 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/sofiatete/Deep_learning_for_medical_imaging/wandb/run-20250205_115021-8rrl7mwb/logs/debug-internal.log
2025-02-05 11:50:21,598 INFO    MainThread:3679 [wandb_init.py:init():756] calling init triggers
2025-02-05 11:50:21,598 INFO    MainThread:3679 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-02-05 11:50:21,598 INFO    MainThread:3679 [wandb_init.py:init():789] starting backend
2025-02-05 11:50:21,598 INFO    MainThread:3679 [wandb_init.py:init():793] sending inform_init request
2025-02-05 11:50:21,599 INFO    MainThread:3679 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-02-05 11:50:21,599 INFO    MainThread:3679 [wandb_init.py:init():808] backend started and connected
2025-02-05 11:50:21,601 INFO    MainThread:3679 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-02-05 11:50:21,603 INFO    MainThread:3679 [wandb_init.py:init():901] updated telemetry
2025-02-05 11:50:21,622 INFO    MainThread:3679 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-02-05 11:51:52,090 ERROR   MainThread:3679 [wandb_init.py:init():1471] error in wandb.init()
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 950, in init
    raise CommError(
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
